######################## default configuration ####################
baseurl = "/"
title = "Backhome Foods"
theme = "restaurant-hugo"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
relativeurls = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

GoogleAnalytics = ""

summaryLength = "7"

# Define the number of posts per page
paginate = 10
############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "Home"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "About Us"
URL = "about-us"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Sauce"
URL = "price"
weight = 4

[[menu.main]]
name = "News"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "Contact Us"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright 2020 - All Rights Reserved. Design and Developed By Themefisher.com"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>BLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "016742 323313"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "Maryland, VA"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "nana@backhomefood.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

######################## Social Icon
[[params.footer.socialLink]]
icon = "facebook"
link = "https://www.facebook.com/backhomefoodco/"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://mobile.twitter.com/backhomefoods"

[[params.footer.socialLink]]
icon = "pinterest"
link = "https://www.pinterest.com/17t3eo732wabwlf0oe4jn3k4z8kdy6/boards/"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://www.instagram.com/backhomefoods/"

[[params.footer.socialLink]]
icon = "linkedin"
link = "https://www.linkedin.com/company/backhome-foods/"
